# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d164b4c4d1c490a56ee07843d6ea6e0de55c201227eb1f965284a2ae99f8a34cbf6c71bc70ecab03fca9ac3013afa768d098dafeac0739dae3a55101fd47ad04

test:
  secret_key_base: 934c729b4b4b697921644da1dfbbe6502ba10b0758e7a727338b4a69ec1d90a62defdfdbd18d2ec2acefc76520c3de8e6bbffde17ef876546fc14790ee688cf8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
